export const BookActionTypes = {    
    FETCH_THEBOOK_START: 'FETCH_THEBOOK_START',
    FETCH_THEBOOK_SUCCESS: 'FETCH_THEBOOK_SUCCESS',
    FETCH_THEBOOK_FAIL : 'FETCH_THEBOOK_FAIL'
}   

export default BookActionTypes